server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
spring:
  application:
    name: foo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leogsilva/config-repo
          basedir: target/config
       